ButtonWithIcon disabled and loading props
paritytech/ink-playground pull request #114
Opened 2021-11-17 09:28 UTC by nmauersberg

This PR introduces optional disabled and loading props to the ButtonWithIcon component and displays the button state accordingly.

A button with loading state is always disabled too.

Tasks:

2021-11-17 09:51 UTC, thought2 commented on packages/components/src/ButtonWithIcon.tsx
> +  const isLoading = loading !== undefined ? loading : false;
`const isLoading = new Boolean(loading)`
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Boolean

2021-11-17 09:51 UTC, thought2 commented on packages/components/src/ButtonWithIcon.tsx
> +    }
I'd suggest to flatten this a bit by using an early return also fow the `isDisabled` case.

2021-11-17 09:51 UTC, thought2 commented on packages/components/src/ButtonWithIcon.tsx
> +          <i className="pi pi-ban mt-1.5 mr-1.5" data-testid={'icon-disabled'} />
I have not seen this pattern with the empty `<i>` before. Is it recommended by tailwind or somewhere else?

2021-11-19 15:47 UTC, achimcc requested changes
- clicking on the compile button yields a small "jump" of the neighbouring Settings button, which shouldn't happen.
- Clicking compile should also toggle the "Compile" button into idle/disabled state, until the compilation is done

2021-11-19 16:32 UTC, nmauersberg commented
@achimcc The small "Jump" you described is coming from the requirement: "The download button should display a animated Spinner when compile state is IN_PROGRESS." in the issue #114 It is instantly in "Result" state, because there is no compilation process running.

I can add the same functionality to the Compile button.

Should it be removed from the "Download" button? Maybe that one should only be disabled, while compilation is running.

2021-11-19 16:40 UTC, achimcc commented
> Edit: Ah, okay, with the merged main branch I see the subtle movement too. I will fix that.

Exactly, the Text button on the right should not move/jump to the left when the state of the button changes ;)

2021-11-22 09:24 UTC, achimcc requested changes
- The buttons still "jump": 
https://www.awesomescreenshot.com/video/6110161?key=7be3db489205ffa7bc8e11965f6b90c0
- Both buttons, Download and Compile should be idle during compilation.
- Without having a downloadable .contract file availabale, the Download button should be disabled.

2021-11-22 11:13 UTC, nmauersberg commented
I cannot reproduce the "jumping" button. It looks like you are missing the latest changes in your screen recording. The compile button would be in loading state too, if they were applied.

This is how it looks for me: https://cloud.deni.one/s/ctDfQ4XooL5RXsX

2021-11-22 15:10 UTC, achimcc approved these changes

2021-11-24 14:25 UTC, merged